USE master;
GO
  IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'Project1')
  BEGIN
      Alter DATABASE Project1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
      DROP DATABASE Project1;
  END;
  GO
CREATE DATABASE Project1;
GO
USE Project1;

CREATE SCHEMA blayer;
GO
CREATE SCHEMA slayer;
GO
CREATE SCHEMA glayer;
GO
